import React from "react";
import { Document, Page, Text, View, StyleSheet, Font } from "@react-pdf/renderer";
import path from "path";

Font.register({
  family: "NotoSansDevanagari",
  fonts: [
    {
      src: path.join(process.cwd(), "public/fonts/NotoSansDevanagari-Regular.ttf"),
      fontWeight: "normal",
    },
    {
      src: path.join(process.cwd(), "public/fonts/NotoSansDevanagari-Bold.ttf"),
      fontWeight: "bold",
    },
  ],
});

function containsDevanagari(text: string): boolean {
  return /[\u0900-\u097F]/.test(text);
}

// Detect if a line is a heading/section title
function isHeading(line: string): boolean {
  const trimmed = line.trim();
  if (!trimmed) return false;
  // Numbered sections: "1.", "1)", "Section 1", "ARTICLE I", "Clause 1"
  if (/^(Section|SECTION|Article|ARTICLE|Clause|CLAUSE)\s/i.test(trimmed)) return true;
  if (/^\d+[\.\)]\s/.test(trimmed)) return true;
  // ALL CAPS lines (at least 3 words, likely a heading)
  if (trimmed === trimmed.toUpperCase() && trimmed.length > 5 && /[A-Z]/.test(trimmed)) return true;
  // Lines ending with colon (like "Definitions:")
  if (/^[A-Z].*:$/.test(trimmed) && trimmed.length < 80) return true;
  return false;
}

const styles = StyleSheet.create({
  page: {
    paddingTop: 50,
    paddingBottom: 60,
    paddingHorizontal: 50,
    fontSize: 11,
    fontFamily: "Helvetica",
    lineHeight: 1.6,
    color: "#000000",
    backgroundColor: "#ffffff",
  },
  pageHindi: {
    paddingTop: 50,
    paddingBottom: 60,
    paddingHorizontal: 50,
    fontSize: 11,
    fontFamily: "NotoSansDevanagari",
    lineHeight: 1.8,
    color: "#000000",
    backgroundColor: "#ffffff",
  },
  title: {
    fontSize: 18,
    fontFamily: "Helvetica-Bold",
    textAlign: "center",
    marginBottom: 20,
    color: "#000000",
  },
  titleHindi: {
    fontSize: 18,
    fontFamily: "NotoSansDevanagari",
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 20,
    color: "#000000",
  },
  heading: {
    fontSize: 11,
    fontFamily: "Helvetica-Bold",
    color: "#000000",
    marginTop: 6,
  },
  content: {
    fontSize: 11,
    color: "#000000",
  },
  footer: {
    position: "absolute",
    bottom: 30,
    left: 50,
    right: 50,
    fontSize: 8,
    color: "#666666",
    textAlign: "center",
    fontFamily: "Helvetica",
  },
  pageNumber: {
    position: "absolute",
    bottom: 20,
    right: 50,
    fontSize: 8,
    color: "#999999",
    fontFamily: "Helvetica",
  },
});

interface DocumentPdfProps {
  title: string;
  content: string;
}

export function DocumentPdf({ title, content }: DocumentPdfProps) {
  const hasHindi = containsDevanagari(content);
  const lines = content.split("\n");

  return (
    <Document>
      <Page size="A4" style={hasHindi ? styles.pageHindi : styles.page} wrap>
        <Text style={hasHindi ? styles.titleHindi : styles.title}>{title}</Text>
        <View>
          {lines.map((line, i) => {
            if (isHeading(line)) {
              return (
                <Text
                  key={i}
                  style={styles.heading}
                  minPresenceAhead={40}
                >
                  {line}
                </Text>
              );
            }
            return (
              <Text key={i} style={styles.content}>
                {line}
              </Text>
            );
          })}
        </View>
        <Text
          style={styles.footer}
          fixed
        >
          Generated by LegalDocs — For reference only. Consult a lawyer for legal advice.
        </Text>
        <Text
          style={styles.pageNumber}
          render={({ pageNumber, totalPages }) => `${pageNumber} / ${totalPages}`}
          fixed
        />
      </Page>
    </Document>
  );
}
