import React from "react";
import { Document, Page, Text, View, StyleSheet, Font } from "@react-pdf/renderer";
import path from "path";

// Register Noto Sans Devanagari for Hindi support
Font.register({
  family: "NotoSansDevanagari",
  fonts: [
    {
      src: path.join(process.cwd(), "public/fonts/NotoSansDevanagari-Regular.ttf"),
      fontWeight: "normal",
    },
    {
      src: path.join(process.cwd(), "public/fonts/NotoSansDevanagari-Bold.ttf"),
      fontWeight: "bold",
    },
  ],
});

const styles = StyleSheet.create({
  page: {
    padding: 50,
    fontSize: 11,
    fontFamily: "Helvetica",
    lineHeight: 1.6,
    color: "#000000",
    backgroundColor: "#ffffff",
  },
  pageHindi: {
    padding: 50,
    fontSize: 11,
    fontFamily: "NotoSansDevanagari",
    lineHeight: 1.8,
    color: "#000000",
    backgroundColor: "#ffffff",
  },
  title: {
    fontSize: 18,
    fontFamily: "Helvetica-Bold",
    textAlign: "center",
    marginBottom: 20,
    color: "#000000",
  },
  titleHindi: {
    fontSize: 18,
    fontFamily: "NotoSansDevanagari",
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 20,
    color: "#000000",
  },
  content: {
    fontSize: 11,
    whiteSpace: "pre-wrap",
    color: "#000000",
  },
  footer: {
    position: "absolute",
    bottom: 30,
    left: 50,
    right: 50,
    fontSize: 8,
    color: "#666666",
    textAlign: "center",
    fontFamily: "Helvetica",
  },
});

// Check if text contains Devanagari characters
function containsDevanagari(text: string): boolean {
  return /[\u0900-\u097F]/.test(text);
}

interface DocumentPdfProps {
  title: string;
  content: string;
}

export function DocumentPdf({ title, content }: DocumentPdfProps) {
  const hasHindi = containsDevanagari(content);
  const paragraphs = content.split("\n");

  return (
    <Document>
      <Page size="A4" style={hasHindi ? styles.pageHindi : styles.page}>
        <Text style={hasHindi ? styles.titleHindi : styles.title}>{title}</Text>
        <View>
          {paragraphs.map((para, i) => (
            <Text key={i} style={styles.content}>
              {para}
            </Text>
          ))}
        </View>
        <Text style={styles.footer}>
          Generated by KanoonSimplified — For reference only. Consult a lawyer for legal advice.
        </Text>
      </Page>
    </Document>
  );
}
