import { Scale, ArrowLeft } from "lucide-react";
import Link from "next/link";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — LegalDocs by KraftAI",
  description:
    "Terms of Service for LegalDocs. Read our terms before using our AI legal document generator.",
};

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen bg-[#030712]">
      <div className="mx-auto max-w-3xl px-6 py-16 lg:px-8">
        <Link
          href="/legal-docs"
          className="inline-flex items-center text-sm text-slate-400 hover:text-orange-500 mb-8"
        >
          <ArrowLeft className="mr-2 h-4 w-4" />
          Back to LegalDocs
        </Link>

        <div className="flex items-center gap-2 mb-8">
          <Scale className="h-6 w-6 text-orange-500" />
          <span className="text-xl font-bold text-white">
            Legal<span className="text-orange-500">Docs</span>
          </span>
        </div>

        <h1 className="text-3xl font-bold text-white mb-2">
          Terms of Service
        </h1>
        <p className="text-slate-400 mb-12">
          Last updated: March 4, 2026
        </p>

        <div className="prose prose-invert prose-slate max-w-none space-y-8 text-slate-300">
          <section>
            <h2 className="text-xl font-semibold text-white">
              1. Acceptance of Terms
            </h2>
            <p>
              By accessing or using LegalDocs (operated by KraftAI, accessible at
              kraftai.in/legal-docs), you agree to be bound by these Terms of
              Service. If you do not agree, do not use the service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white">
              2. Not Legal Advice
            </h2>
            <p>
              <strong>
                LegalDocs is NOT a law firm and does NOT provide legal advice.
              </strong>{" "}
              Documents generated by our platform are created using AI and are for
              reference purposes only. They are based on general Indian law
              templates and may not cover specific legal requirements in your
              situation.
            </p>
            <p>
              We strongly recommend consulting a qualified lawyer before relying on
              any document generated through our service, especially for matters
              involving significant financial or legal obligations.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white">
              3. Service Description
            </h2>
            <p>
              LegalDocs provides an AI-powered platform to generate legal documents
              including Rental Agreements, Non-Disclosure Agreements (NDAs), and
              Freelancer Contracts in multiple Indian languages. Users provide
              input, and our AI generates formatted documents based on that input.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white">
              4. User Accounts
            </h2>
            <ul className="list-disc pl-6 space-y-1">
              <li>
                You must sign in using Google Authentication to access paid
                features.
              </li>
              <li>
                You are responsible for maintaining the security of your account.
              </li>
              <li>
                You must provide accurate information when generating documents.
              </li>
              <li>
                We reserve the right to suspend accounts that violate these terms.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white">
              5. Free Documents & Pricing
            </h2>
            <ul className="list-disc pl-6 space-y-1">
              <li>
                Each user gets 2 free document generations.
              </li>
              <li>
                After free documents are exhausted, documents are available at the
                prices listed on the platform (starting at ₹99).
              </li>
              <li>
                We reserve the right to change pricing at any time. Existing
                purchased documents will not be affected.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white">
              6. Payments & Refunds
            </h2>
            <ul className="list-disc pl-6 space-y-1">
              <li>
                All payments are processed securely through Razorpay.
              </li>
              <li>
                Prices are listed in Indian Rupees (INR) and include applicable
                taxes.
              </li>
              <li>
                <strong>Refund Policy:</strong> Since documents are generated
                instantly and delivered digitally, refunds are generally not
                available once a document has been generated. If you experience a
                technical issue where a document was not delivered after payment,
                contact us at hritik242000@gmail.com within 7 days for resolution.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white">
              7. Intellectual Property
            </h2>
            <ul className="list-disc pl-6 space-y-1">
              <li>
                The LegalDocs platform, branding, templates, and underlying
                technology are owned by KraftAI.
              </li>
              <li>
                Documents you generate are yours to use. You retain ownership of
                the content you provide.
              </li>
              <li>
                You may not reproduce, distribute, or create derivative works of
                our platform or templates.
              </li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white">
              8. Prohibited Uses
            </h2>
            <p>You agree not to:</p>
            <ul className="list-disc pl-6 space-y-1">
              <li>Use the service for any illegal purpose.</li>
              <li>Generate documents with false or fraudulent information.</li>
              <li>
                Attempt to reverse-engineer, scrape, or exploit the platform.
              </li>
              <li>Interfere with the service&apos;s operation or security.</li>
              <li>Resell or redistribute generated documents commercially.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white">
              9. Limitation of Liability
            </h2>
            <p>
              To the maximum extent permitted by law, KraftAI shall not be liable
              for:
            </p>
            <ul className="list-disc pl-6 space-y-1">
              <li>
                Any legal disputes, losses, or damages arising from the use of
                generated documents.
              </li>
              <li>
                Inaccuracies or omissions in AI-generated content.
              </li>
              <li>
                Any indirect, incidental, special, or consequential damages.
              </li>
              <li>
                Loss of data, revenue, or profits related to use of the service.
              </li>
            </ul>
            <p>
              Our total liability shall not exceed the amount paid by you for the
              specific document in question.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white">
              10. Disclaimer of Warranties
            </h2>
            <p>
              The service is provided &quot;as is&quot; and &quot;as available&quot; without
              warranties of any kind, whether express or implied. We do not
              guarantee that documents will be legally enforceable in all
              jurisdictions or situations.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white">
              11. Governing Law
            </h2>
            <p>
              These terms are governed by and construed in accordance with the laws
              of India. Any disputes shall be subject to the exclusive jurisdiction
              of the courts in India.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white">
              12. Changes to Terms
            </h2>
            <p>
              We may modify these terms at any time. Changes take effect when
              posted. Continued use of the service constitutes acceptance of
              modified terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-white">
              13. Contact Us
            </h2>
            <p>
              For questions about these Terms of Service, contact us at:{" "}
              <a
                href="mailto:hritik242000@gmail.com"
                className="text-orange-500 hover:underline"
              >
                hritik242000@gmail.com
              </a>
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
